version: '2'
services:

  ngroktunnel:
    build:
      context: .
    image: gtriggiano/ngrok-tunnel:development
    ports:
      - "4040:4040"
    environment:
      NGROK_REGION: eu
      TARGET_HOST: testservice
      TARGET_PORT: 5000
    depends_on:
      - testservice

  testservice:
    image: gtriggiano/dummy-http-service
    ports:
      - "8080:5000"
